id: A45E012E0
title: In Praise of the Eight Siddhas
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:02:14.023250
  last_modified_at: 2022-02-28 23:02:14.023256
