id: A45E012E0
title: 'An Envoy for Swiftly Invoking the Blessings of Definitive Meaning: Calling
  the Great Omniscient Jonangpa from Afar'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:02:14.017801
  last_modified_at: 2022-02-28 23:02:14.017807
